name: azure-keyvault-payment-crypto-poc-compose

services:
  postgres:
    container_name: kvpc-postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
